using System.Net.Mime;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Jellyfin.Plugin.YouTubeSync.Controllers;

/// <summary>
/// HTTP API controller that resolves a YouTube video ID to a playable stream.
///
/// Endpoint: GET /YouTubeSync/resolve/{videoId}
///
/// The .strm files generated by <see cref="SyncService"/> point to this endpoint.
/// When a Jellyfin client initiates playback it fetches this URL, which in turn calls yt-dlp
/// to pick the best available stream:
///   • Progressive (combined video+audio): HTTP 302 redirect to the CDN URL.
///   • DASH (separate video+audio):        yt-dlp merges both streams on-the-fly via FFmpeg
///     and the controller pipes the merged Matroska output directly to the response body.
///     This requires FFmpeg to be accessible by yt-dlp (configured via <c>FfmpegPath</c>
///     in the plugin settings, or on the system PATH).
/// </summary>
[ApiController]
[Route("YouTubeSync")]
[Produces(MediaTypeNames.Application.Json)]
public class YouTubeSyncController : ControllerBase
{
    private readonly ResolveService _resolveService;
    private readonly YtDlpService _ytDlpService;
    private readonly ILogger<YouTubeSyncController> _logger;

    /// <summary>Initializes a new instance of the <see cref="YouTubeSyncController"/> class.</summary>
    public YouTubeSyncController(
        ResolveService resolveService,
        YtDlpService ytDlpService,
        ILogger<YouTubeSyncController> logger)
    {
        _resolveService = resolveService;
        _ytDlpService = ytDlpService;
        _logger = logger;
    }

    /// <summary>
    /// Resolves a YouTube video ID to the best available stream and serves it to the client.
    /// Returns a 302 redirect for progressive (combined) streams, or streams DASH video+audio
    /// muxed on-the-fly when only split DASH formats are available.
    /// Returns 503 when no compatible format can be found at all.
    /// </summary>
    /// <param name="videoId">The YouTube video ID (e.g. dQw4w9WgXcQ).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>302 redirect, streaming Matroska body, or 503 on failure.</returns>
    [HttpGet("resolve/{videoId}")]
    [ProducesResponseType(StatusCodes.Status302Found)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public async Task<IActionResult> ResolveVideo(string videoId, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(videoId) || videoId.Length > 32)
        {
            return BadRequest("Invalid video ID.");
        }

        _logger.LogInformation("Resolve request for video {VideoId}", videoId);

        var format = await _resolveService.ResolveAsync(videoId, cancellationToken).ConfigureAwait(false);
        if (format is null)
        {
            _logger.LogWarning(
                "No compatible format available for {VideoId}. Returning 503.",
                videoId);
            return StatusCode(
                StatusCodes.Status503ServiceUnavailable,
                $"No compatible stream found for video '{videoId}'.");
        }

        // Progressive: simple redirect – Jellyfin/FFmpeg fetches the CDN URL directly.
        if (!format.NeedsMuxing)
        {
            _logger.LogDebug(
                "Redirecting {VideoId} to progressive CDN URL (height={Height}p)",
                videoId,
                format.Height);
            return Redirect(format.VideoUrl);
        }

        // DASH: pipe the yt-dlp merged stream straight to the response body.
        // yt-dlp uses FFmpeg internally to merge the two DASH streams into Matroska.
        _logger.LogInformation(
            "Serving DASH stream for {VideoId} via yt-dlp proxy (height={Height}p, "
            + "video={VFmt}, audio={AFmt})",
            videoId,
            format.Height,
            format.VideoFormatId,
            format.AudioFormatId);

        Response.ContentType = "video/x-matroska";
        Response.StatusCode = StatusCodes.Status200OK;

        await _ytDlpService
            .StreamVideoAsync(videoId, format.VideoFormatId, format.AudioFormatId!, Response.Body, cancellationToken)
            .ConfigureAwait(false);

        // The body has already been written; EmptyResult prevents the framework
        // from writing anything additional to the response.
        return new EmptyResult();
    }

    /// <summary>
    /// Fetches metadata (title, description, thumbnail URL, type) for a YouTube channel or playlist URL.
    /// Called by the admin configuration UI to auto-populate source details.
    /// </summary>
    /// <param name="url">The YouTube channel or playlist URL.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A <see cref="SourceInfo"/> object, or 400/503 on error.</returns>
    [HttpGet("source-info")]
    [ProducesResponseType(typeof(SourceInfo), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public async Task<IActionResult> GetSourceInfo([FromQuery] string url, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(url))
        {
            return BadRequest("url query parameter is required.");
        }

        _logger.LogInformation("Source-info request for URL {Url}", url);

        var info = await _ytDlpService.GetSourceInfoAsync(url, cancellationToken).ConfigureAwait(false);
        if (info is null)
        {
            return StatusCode(
                StatusCodes.Status503ServiceUnavailable,
                "Failed to fetch source info from YouTube. Check that yt-dlp is installed and the URL is valid.");
        }

        return Ok(info);
    }
}
